In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [78]:
rawdata = pd.read_csv('/Users/Janey_jiayan/Downloads/Humana_Data/HMAHCC_COMP.csv')

/Users/Janey_jiayan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [79]:
len(rawdata['id'].unique())

14000

In [80]:
rawdata.head()

,id,event_descr,event_attr1,event_attr2,event_attr3,event_attr4,event_attr5,event_attr6,event_attr7,event_attr8,event_attr9,event_attr10,Days,PAY_DAY_SUPPLY_CNT,PAYABLE_QTY,MME,DRUG_TYPE,Specialty,Specialty2,Specialty3
0,ID10010854159,RX Claim - Paid,BIGUANIDES,NaN,5,2.35,METFORMIN HCL,DIABETES,NaN,METFORMIN HCL TAB 500 MG,2.65,27250050.0,-664,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ID10010854159,RX Claim - Paid,BETA BLOCKERS CARDIO-SELECTIVE,NaN,5,2.35,ATENOLOL,CARDIO,NaN,ATENOLOL TAB 25 MG,2.65,33200020.0,-659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ID10010854159,RX Claim - Rejected,DENY DUE TO ERRORS,"SYMPTOMS, SIGNS, ILL DEFINED CONDITIONS",NO DUAL COVERAGE,COPAY EXCEPTIONS,ATENOLOL,ATENOLOL TAB 25 MG,7.81108e+08,90,5.00,NaN,-659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ID10010854159,RX Claim - Paid,FLUOROQUINOLONES,NaN,5.8,3.15,CIPROFLOXACIN HCL,INF-ANTIBIOTICS,NaN,CIPROFLOXACIN HCL TAB 500 MG (BASE EQUIV),2.65,5000020.0,-646,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ID10010854159,RX Claim - Paid,HMG COA REDUCTASE INHIBITORS,NaN,13,10.35,PRAVASTATIN SODIUM,CARDIO,NaN,PRAVASTATIN SODIUM TAB 20 MG,2.65,39400065.0,-646,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
test = rawdata[rawdata['Days'] >= 0]

In [82]:
test_RX_notnull = test.loc[(test['event_descr']=='RX Claim - Paid') & (test['MME'].notnull())]

In [83]:
test_RX_notnull.head()

,id,event_descr,event_attr1,event_attr2,event_attr3,event_attr4,event_attr5,event_attr6,event_attr7,event_attr8,event_attr9,event_attr10,Days,PAY_DAY_SUPPLY_CNT,PAYABLE_QTY,MME,DRUG_TYPE,Specialty,Specialty2,Specialty3
194,ID10010854159,RX Claim - Paid,OPIOID AGONISTS,NaN,1.83,1.38,TRAMADOL HCL,PAIN,NaN,TRAMADOL HCL TAB 50 MG,0.45,65100095.0,0,5.0,15.0,15.0,IR,Internal Medicine Critical Care Medicine,Hospitalist,Family Practice
329,ID10010854159,RX Claim - Paid,OPIOID COMBINATIONS,NaN,5,4.45,ACETAMINOPHEN/CODEINE,PAIN,NaN,ACETAMINOPHEN W/ CODEINE TAB 300-30 MG,0.55,65991002.0,706,5.0,14.0,12.6,IR,Dentist General Practice,Dentist,NaN
397,ID10013863216,RX Claim - Paid,OPIOID AGONISTS,NaN,11.05,0,TRAMADOL HCL,PAIN,NaN,TRAMADOL HCL TAB 50 MG,11.05,65100095.0,0,90.0,180.0,10.0,IR,Family Practice,Family Practice Adult Medicine,NaN
405,ID10013863216,RX Claim - Paid,OPIOID AGONISTS,NaN,11.05,0,TRAMADOL HCL,PAIN,NaN,TRAMADOL HCL TAB 50 MG,11.05,65100095.0,94,90.0,180.0,10.0,IR,Family Practice,Family Practice Adult Medicine,NaN
417,ID10013863216,RX Claim - Paid,OPIOID AGONISTS,NaN,11.03,0,TRAMADOL HCL,PAIN,NaN,TRAMADOL HCL TAB 50 MG,11.03,65100095.0,253,90.0,180.0,10.0,IR,Family Practice,Family Practice Adult Medicine,NaN

In [87]:
len(test_RX_notnull['id'].unique())

13948

In [88]:
Id_Notnull = test_RX_notnull['id'].unique()

In [89]:
Id_Notnull

array(['ID10010854159', 'ID10013863216', 'ID10024447278', ...,
       'ID99985278397', 'ID99987501651', 'ID99994197161'], dtype=object)

In [90]:
joined_tbl = pd.read_csv('/Users/Janey_jiayan/Downloads/Humana_Data/joined_tbl.csv')

In [91]:
len(joined_tbl['id'].unique())

13990

In [92]:
joined_tbl = joined_tbl.drop(joined_tbl.columns[0],axis=1)

In [93]:
joined_tbl.head()

,id,#_of_FPC,#_of_InbCall_Mrb,#_of_InbCall_Prov,#_of_CAD,#_of_CHF,#_of_CPD,#_of_Diabetes,#_of_Hypertension,#_of_Surgery,Most_Recent_Day_Surgery,Avg_Amt_Spent_Surgery,Total_Amt_FPC,Total_Amt_CAD,Total_Amt_CHF,Total_Amt_CPD,Total_Amt_Diabetes,Total_Amt_Hypertension
0,ID10010854159,43.0,26.0,8.0,0.0,0.0,0.0,0.0,0.0,1.0,-421.0,2314.00,23227.94,0.0,0.0,0.0,0.0,0.0
1,ID10013863216,19.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-200.0,12337.42,18282.46,0.0,0.0,0.0,0.0,0.0
2,ID10024447278,21.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,3126.90,0.0,0.0,0.0,0.0,0.0
3,ID1002482139,149.0,6.0,5.0,1.0,0.0,1.0,0.0,0.0,1.0,-742.0,50042.33,136843.88,137.0,0.0,137.0,0.0,0.0
4,ID1003386406,48.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,76559.83,0.0,0.0,0.0,0.0,0.0

In [94]:
joined_tbl_fin = joined_tbl.loc[joined_tbl['id'].isin(Id_Notnull),]

In [95]:
joined_tbl_fin

,id,#_of_FPC,#_of_InbCall_Mrb,#_of_InbCall_Prov,#_of_CAD,#_of_CHF,#_of_CPD,#_of_Diabetes,#_of_Hypertension,#_of_Surgery,Most_Recent_Day_Surgery,Avg_Amt_Spent_Surgery,Total_Amt_FPC,Total_Amt_CAD,Total_Amt_CHF,Total_Amt_CPD,Total_Amt_Diabetes,Total_Amt_Hypertension
0,ID10010854159,43.0,26.0,8.0,0.0,0.0,0.0,0.0,0.0,1.0,-421.0,2314.000000,23227.94,0.0,0.00,0.00,0.00,0.0
1,ID10013863216,19.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-200.0,12337.420000,18282.46,0.0,0.00,0.00,0.00,0.0
2,ID10024447278,21.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,3126.90,0.0,0.00,0.00,0.00,0.0
3,ID1002482139,149.0,6.0,5.0,1.0,0.0,1.0,0.0,0.0,1.0,-742.0,50042.330000,136843.88,137.0,0.00,137.00,0.00,0.0
4,ID1003386406,48.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,76559.83,0.0,0.00,0.00,0.00,0.0
5,ID10036289882,7.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1409.00,0.0,0.00,0.00,0.00,0.0
6,ID10036954381,29.0,23.0,18.0,1.0,0.0,0.0,0.0,0.0,1.0,-560.0,4643.000000,9247.55,42.0,0.00,0.00,0.00,0.0
7,ID10055739763,25.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,4732.16,0.0,0.00,0.00,0.00,0.0
8,ID10074598346,95.0,22.0,9.0,0.0,1.0,0.0,0.0,0.0,1.0,-246.0,1452.000000,80296.84,0.0,185.00,0.00,0.00,0.0
9,ID10081072715,18.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,12070.40,0.0,0.00,0.00,0.00,0.0
10,ID1008136105,56.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,32602.66,0.0,0.00,35.00,0.00,0.0
11,ID10085004805,25.0,23.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,5135.55,0.0,0.00,0.00,0.00,0.0
12,ID10085392189,19.0,12.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,30215.00,0.0,0.00,752.00,0.00,0.0
13,ID10112532931,26.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,42134.52,2513.0,0.00,0.00,2513.00,640.0
14,ID10119459922,55.0,20.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,13678.25,0.0,0.00,0.00,20.55,0.0
15,ID10125698107,31.0,36.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0,-515.0,13372.950000,24597.25,0.0,0.00,0.00,0.00,0.0
16,ID10126196784,24.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,65243.56,0.0,0.00,0.00,0.00,0.0
17,ID1013630023,86.0,22.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,49830.44,0.0,109.00,0.00,0.00,0.0
18,ID10137326880,84.0,16.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,25767.23,0.0,0.00,0.00,0.00,0.0
19,ID10144726843,89.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,-310.0,5395.340000,95718.90,0.0,0.00,0.00,0.00,0.0
20,ID10155139868,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1854.92,0.0,0.00,0.00,0.00,0.0
21,ID10158166620,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,3404.00,0.0,0.00,0.00,0.00,0.0
22,ID10166893764,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,-9.0,34370.840000,50642.45,0.0,0.00,0.00,0.00,0.0
23,ID10167700196,86.0,82.0,8.0,0.0,0.0,0.0,1.0,0.0,1.0,-428.0,41851.790000,239670.07,0.0,0.00,0.00,1213.00,0.0
24,ID10169051312,34.0,6.0,10.0,0.0,0.0,1.0,0.0,0.0,1.0,-385.0,995.000000,10877.15,0.0,0.00,0.01,0.00,0.0
25,ID10180352120,69.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,-102.0,3249.580000,25363.83,0.0,0.00,0.00,0.00,0.0
26,ID10189080475,99.0,31.0,3.0,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,72568.19,0.0,0.00,0.00,266.00,1078.0
27,ID10194867854,7.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1432.00,0.0,0.00,0.00,0.00,0.0
28,ID10201747254,90.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,24193.45,0.0,0.00,0.00,0.00,0.0
29,ID10203805803,35.0,5.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,4354.00,0.0,0.00,195.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13960,ID99819880491,67.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,51110.82,0.0,0.00,0.00,0.00,0.0
13961,ID9982180832,39.0,10.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-1033.0,850.000000,14891.19,0.0,0.00,0.00,0.00,0.0
13962,ID99824085831,201.0,22.0,10.0,1.0,1.0,0.0,0.0,0.0,6.0,-248.0,29280.703333,188641.55,91.0,0.00,0.00,0.00,0.0
13963,ID99827357428,19.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-231.0,5561.000000,15079.64,0.0,0.00,0.00,0.00,0.0
13964,ID99832270387,69.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,14415.36,0.0,0.00,85.00,0.00,0.0
13965,ID99844174319,98.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,19019.27,0.0,0.00,0.00,0.00,0.0
13966,ID99851961387,29.0,7.0,6.0,0.0,0.0,1.0,1.0,1.0,2.0,-169.0,9104.440000,38001.63,0.0,0.00,65.00,47.00,212.0
13967,ID99853738490,49.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,6564.00,0.0,0.00,0.00,0.00,0.0
13968,ID99865372013,57.0,12.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,12283.18,0.0,0.00,0.00,0.00,0.0
13969,ID99866353021,78.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,-334.0,2911.076667,74438.04,0.0,0.00,0.00,0.00,0.0
13970,ID99870677385,40.0,8.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,15296.11,0.0,0.00,0.00,0.00,0.0
13971,ID99877095827,48.0,19.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,9692.53,0.0,0.00,0.00,0.00,0.0
13972,ID99888932285,28.0,14.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,38365.71,0.0,0.00,0.00,0.00,0.0
13973,ID99893580330,15.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,7070.00,0.0,0.00,0.00,0.00,0.0
13974,ID99899080861,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,588.39,0.0,0.00,0.00,0.00,0.0
13975,ID99899156391,38.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,12759.73,0.0,0.00,0.00,0.00,0.0
13976,ID99906098656,35.0,1.0,5.0,0.0,0.0,0.0,0.0,1.0,3.0,-16.0,16145.980000,25693.50,0.0,0.00,0.00,0.00,175.0
13977,ID99906998779,118.0,7.0,37.0,0.0,0.0,0.0,0.0,1.0,5.0,-246.0,33846.966000,127694.67,0.0,0.00,0.00,0.00,645.0
13978,ID99915109341,81.0,52.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,33427.50,0.0,0.00,0.00,0.00,0.0
13979,ID99915340915,10.0,13.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0,NaN,NaN,6386.12,0.0,0.00,224.00,0.00,126.0
13980,ID99922543950,42.0,0.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,-191.0,21300.030000,36205.41,0.0,0.00,0.00,0.00,0.0
13981,ID99932051589,81.0,15.0,26.0,0.0,1.0,0.0,0.0,1.0,8.0,-7.0,22229.521250,149257.03,0.0,2508.36,0.00,0.00,1200.0
13982,ID9993577054,152.0,2.0,10.0,0.0,0.0,0.0,0.0,0.0,5.0,-84.0,6046.738000,195314.90,0.0,0.00,0.00,0.00,0.0
13983,ID99940102826,72.0,6.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,-831.0,5281.000000,27824.96,0.0,0.00,0.00,0.00,0.0
13984,ID99952965555,46.0,9.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,-406.0,3025.000000,21644.92,0.0,0.00,175.00,0.00,0.0
13985,ID99971049558,25.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-469.0,1957.000000,10126.33,0.0,0.00,0.00,0.00,0.0
13986,ID99975648894,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,2359.00,0.0,0.00,0.00,0.00,0.0
13987,ID99985278397,39.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,-541.0,3996.850000,20375.00,0.0,0.00,0.00,0.00,0.0
13988,ID99987501651,14.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,5606.76,0.0,0.00,0.00,0.00,0.0
13989,ID99994197161,6.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,877.00,0.0,0.00,0.00,0.00,0.0